% Run twitter examples

t01_cornealRefraction
t02_pupilWithRotation
t03_centersOfRotation
t04_aziElelRotation
t05_lineOfSight
t06_fixationPose
t07_torsion
t08_ListingsLaw
t09_rotationalAsymmetry
t10_glintStationary
t11_glintMoving
t12_eyePoseSearch